### ISSUE TITLE
开启aes加密时，支付宝方报参数错误

### ISSUE THREAD

**Issue by zhyfor** [Yurunsoft/PaySDK#12]
https://doc.yurunsoft.com/PaySDK/74
对接手机网站支付：在关掉aes加密时，一切正常，在打开加密时，支付宝方 报 参数出错。
https://static.dingtalk.com/media/lADPDgQ9rfGPQqnNBQDNAoA_640_1280.jpg_620x10000q90g.jpg?bizType=im
与支付宝客服沟通后，他们也不能判断paySDK中的加密方式是否有问题，并给了一个他们官方SDK的加密代码，如下：
![I)0 K6032)I3WJ Y9RX5HOY](https://user-images.githubusercontent.com/6119494/72709646-5419bb00-3ba0-11ea-8b25-919ba09cb8a7.png)
支付宝官方SDK地址：
https://docs.open.alipay.com/54/103419

**Comment by Yurunsoft** [comment]
PaySDK的aes加密结果与官方SDK加密结果一致，请检查其他配置
