### ISSUE TITLE
支付宝小程序支付

### ISSUE THREAD

**Issue by shuqingzai** [Yurunsoft/PaySDK#14]
希望支持[支付宝小程序](https://opendocs.alipay.com/mini/introduce/pay)，谢谢大佬

**Comment by Yurunsoft** [comment]
已在 `dev` 分支中实现，可以尝试把`composer`中的paysdk版本更新为`dev-dev`

demo参考：<https://github.com/Yurunsoft/PaySDK/blob/bc5f2d3185912c56c4fe2228c14002f828c3c907/test/AlipayApp/miniapp_pay.php>

有问题请及时反馈
