### ISSUE TITLE
支付宝公钥证书加密方式支持

### ISSUE THREAD

**Issue by goleden** [Yurunsoft/PaySDK#16]
https://opendocs.alipay.com/open/291/105971

![image](https://user-images.githubusercontent.com/9799444/78853235-f5523800-7a50-11ea-97c1-05a15e9618f2.png)

希望能够支持下。

**Comment by Yurunsoft** [comment]
稍后发布 v3.0.1 版本更新后即可使用
文档：https://doc.yurunsoft.com/PaySDK/85#%E5%85%AC%E9%92%A5%E8%AF%81%E4%B9%A6%E7%AD%BE%E5%90%8D%E5%92%8C%E9%AA%8C%E7%AD%BE%E9%85%8D%E7%BD%AE
