### ISSUE TITLE
支付宝使用证书公钥匙提示

### ISSUE THREAD

**Issue by LRRun** [Yurunsoft/PaySDK#24]
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in  /vendor/yurunsoft/pay-sdk/src/Lib/CertUtil.php on line 86

-------
/**
     * 0x转高精度数字
     * @param $hex
     * @return int|string
     */
    public static function hex2dec($hex)
    {
        $dec = 0;
        $len = strlen($hex);
        for ($i = 1; $i <= $len; $i++)
        {
            $dec = bcadd($dec, bcmul(strval(hexdec($hex[$i - 1])), bcpow('16', strval($len - $i))));
        }
        return $dec;
    }

**Comment by Yurunsoft** [comment]
https://github.com/Yurunsoft/PaySDK/pull/25
