### ISSUE TITLE
支付宝 AES 的支持有计划吗？ 

### ISSUE THREAD

**Issue by hh-Ink** [Yurunsoft/PaySDK#34]
![image](https://user-images.githubusercontent.com/16871357/151112123-a9d2e9e5-9053-4073-808e-aee5b6b8ac62.png)

接支付宝的时候，感觉又一层加密会更安全，所以设置了 AES 的key。发现包不支持，支付宝还不支持取消。框架用的hyperf，现在只能用 class_map 替换需要加密和解密的类，总有种不踏实的感觉，希望官方可以原生支持。

另外还有几个接口要求强制开启 AES，如果业务有涉及用到。支付改起来也是灾难性的

**Comment by Yurunsoft** [comment]
暂无精力，开源项目欢迎所有人来贡献一份力
